using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Xml.Serialization;

namespace OpenMetaverse.Rendering;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

/// <remarks />
[GeneratedCode("xsd", "4.0.30319.1")]
[Serializable]
[DesignerCategory("code")]
[XmlRoot("linden_skeleton", Namespace = "", IsNullable = false)]
public partial class LindenSkeleton
{
    private Joint boneField;

    private string num_bonesField;

    private string num_collision_volumesField;

    private float versionField;

    private bool versionFieldSpecified;

    /// <remarks />
    public Joint bone
    {
        get => boneField;
        set => boneField = value;
    }

    /// <remarks />
    [XmlAttribute]
    public float version
    {
        get => versionField;
        set => versionField = value;
    }

    /// <remarks />
    [XmlIgnore]
    public bool versionSpecified
    {
        get => versionFieldSpecified;
        set => versionFieldSpecified = value;
    }

    /// <remarks />
    [XmlAttribute(DataType = "positiveInteger")]
    public string num_bones
    {
        get => num_bonesField;
        set => num_bonesField = value;
    }

    /// <remarks />
    [XmlAttribute(DataType = "positiveInteger")]
    public string num_collision_volumes
    {
        get => num_collision_volumesField;
        set => num_collision_volumesField = value;
    }
}

/// <remarks />
[GeneratedCode("xsd", "4.0.30319.1")]
[Serializable]
[DesignerCategory("code")]
public class Joint : JointBase
{
    private Joint[] boneField;

    private CollisionVolume[] collision_volumeField;

    private float[] pivotField;

    /// <remarks />
    [XmlElement("collision_volume")]
    public CollisionVolume[] collision_volume
    {
        get => collision_volumeField;
        set => collision_volumeField = value;
    }

    /// <remarks />
    [XmlElement("bone")]
    public Joint[] bone
    {
        get => boneField;
        set => boneField = value;
    }

    /// <remarks />
    [XmlAttribute]
    public float[] pivot
    {
        get => pivotField;
        set => pivotField = value;
    }
}

/// <remarks />
[GeneratedCode("xsd", "4.0.30319.1")]
[Serializable]
[DesignerCategory("code")]
public class CollisionVolume : JointBase
{
}

/// <remarks />
[XmlInclude(typeof(Joint))]
[XmlInclude(typeof(CollisionVolume))]
[GeneratedCode("xsd", "4.0.30319.1")]
[Serializable]
[DesignerCategory("code")]
public class JointBase
{
    private string nameField;

    private float[] posField;

    private float[] rotField;

    private float[] scaleField;

    /// <remarks />
    [XmlAttribute(DataType = "token")]
    public string name
    {
        get => nameField;
        set => nameField = value;
    }

    /// <remarks />
    [XmlAttribute]
    public float[] pos
    {
        get => posField;
        set => posField = value;
    }

    /// <remarks />
    [XmlAttribute]
    public float[] rot
    {
        get => rotField;
        set => rotField = value;
    }

    /// <remarks />
    [XmlAttribute]
    public float[] scale
    {
        get => scaleField;
        set => scaleField = value;
    }
}